language: node_js

node_js:
  - '10'
  - '12'
  - 'node'

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS node_ts_starter_test;'

install:
  - docker-compose up -d
  - npm install
  - npm run migrate

script:
  - npm run build
  - npm run test

services:
  - mysql

env:
  global:
    - NODE_ENV=test
    - DB_ACTIVE=active
    - DB_ACTIVE=true
    - DB_HOST=localhost
    - DB_PORT=27017
    - DB_NAME=node_ts_starter_test
    - DB_USERNAME=
    - DB_PASSWORD=
    - SQL_DIALECT=mysql
    - SQL_HOST=localhost
    - SQL_PORT=3306
    - SQL_NAME=node_ts_starter_test
    - SQL_USERNAME=travis
    - SQL_PASSWORD=
    - ENABLE_MESSAGE_BROKER=true
