version: '3.8'
services:
  mongo-node-ts:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017

  zookeeper-node-ts:
    container_name: zookeeper-node-ts
    image: zookeeper:3.5.5
    restart: always
    hostname: zookeeper-node-ts
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  kafka-node-ts:
    container_name: kafka-node-ts
    image: 'wurstmeister/kafka'
    depends_on:
      - zookeeper-node-ts
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-node-ts:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
