version: '3.5'
services:
  mongo-node-ts:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017

  zookeeper-node-ts:
    image: zookeeper
    restart: always
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  kafka-node-ts:
    image: 'wurstmeister/kafka'
    depends_on:
      - zookeeper-node-ts
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: localhost
